# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
image: omalaspinas/palabos:latest
    
cache:
    untracked: false
    key: "$CI_PROJECT_ID"
    
stages:
    - build_examples
    - build_utility
    - deploy
    # - build_examples_cmake
    # - build_utility_cmake

#test_pypal:
#    stage: build
#    
#    script: 
#        - apt-get update
#        - apt-get install -y swig python-dev
#        - export PALABOS_ROOT=`pwd`
#        - git clone git@gitlab.com:flowkit/pypal-web.git
#        - cd pypal-web/scripted-palabos/src
#        - export PYPAL_ROOT=`pwd`
#        - make
        
# Test compilation in the examples directory
examples:
    stage: build_examples

    only:
        - master
    
    script: 
        - pwd
        - cd examples
        - make optimize="false"

# Test compilation in the utility directory
utility:
    stage: build_utility

    only:
        - master
    
    script: 
        - pwd
        - cd utility
        - make optimize="false"
        
## Test compilation in the examples directory
# examples_cmake:
#     stage: build_examples

#     only:
#         - master
#         - cmake
    
#     script: 
#         - pwd
#         - cd examples
#         - ./cmake_all.sh

## Test compilation in the utility directory
# utility_cmake:
#     stage: build_utility

#     only:
#         - master
#         - cmake
    
#     script: 
#         - pwd
#         - cd utility
#         - ./cmake_all.sh

pages:
    stage: deploy
    script:
        - pwd
        - mkdir -p public/docs
        - doxygen Doxyfile
    artifacts:
        paths:
        - public
    only:
        - master

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - ./runmytests.sh
